"""
Activity model for MongoDB persistence
"""

from datetime import datetime

from pydantic import BaseModel, Field


class Activity(BaseModel):
    """
    Persisted activity generated by DestinationResearchAgent.
    MongoDB will assign _id automatically.
    """

    trip_id: str = Field(..., description="Associated trip id")
    name: str = Field(..., description="Activity name")
    category: str = Field(
        ..., description="One of Food, Nightlife, Adventure, Culture, Relax, Nature, Other"
    )
    rough_cost: int | None = Field(default=None, description="Approx per-person cost")
    duration_min: int | None = Field(default=None, description="Approx duration in minutes")
    lat: float | None = Field(default=None, description="Latitude if known")
    lng: float | None = Field(default=None, description="Longitude if known")
    tags: list[str] = Field(default_factory=list, description="Additional tags")
    fits: list[str] = Field(default_factory=list, description="Member ids who likely enjoy this")
    score: float = Field(default=0.0, description="0..1 ranking score")
    rationale: str = Field(default="", description="Short explanation of the fit")

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    class Config:
        json_schema_extra = {
            "example": {
                "trip_id": "6911a4b00ef8e4358798cb05",
                "name": "Shibuya Crossing",
                "category": "Adventure",
                "rough_cost": 0,
                "duration_min": 45,
                "lat": 35.6597,
                "lng": 139.7005,
                "tags": ["Adventure", "Culture"],
                "fits": ["u5", "u6"],
                "score": 0.9,
                "rationale": "Iconic urban experience matching adventure and culture vibes.",
            }
        }
